/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    AutoComplete: typeof import('primevue/autocomplete')['default']
    Button: typeof import('primevue/button')['default']
    Chatbox: typeof import('./src/components/Chatbox.vue')['default']
    ChatboxHello: typeof import('./src/components/ChatboxHello.vue')['default']
    ChatboxMarkdownContent: typeof import('./src/components/ChatboxMarkdownContent.vue')['default']
    ChatboxReactPosts: typeof import('./src/components/ChatboxReactPosts.vue')['default']
    ChatInput: typeof import('./src/components/ChatInput.vue')['default']
    Checkbox: typeof import('primevue/checkbox')['default']
    ConfirmPopup: typeof import('primevue/confirmpopup')['default']
    Demos: typeof import('./src/components/Demos.vue')['default']
    Dialog: typeof import('primevue/dialog')['default']
    FloatColorModeButton: typeof import('./src/components/FloatColorModeButton.vue')['default']
    FloatIconButton: typeof import('./src/components/FloatIconButton.vue')['default']
    FloatThreadConfigButton: typeof import('./src/components/FloatThreadConfigButton.vue')['default']
    FormItem: typeof import('./src/components/FormItem.vue')['default']
    HeroPattern: typeof import('./src/components/HeroPattern.vue')['default']
    InputText: typeof import('primevue/inputtext')['default']
    Logo: typeof import('./src/components/Logo.vue')['default']
    ModelAutoComplete: typeof import('./src/components/ModelAutoComplete.vue')['default']
    Navbar: typeof import('./src/components/Navbar.vue')['default']
    ProgressSpinner: typeof import('primevue/progressspinner')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    Select: typeof import('primevue/select')['default']
    Settings: typeof import('./src/components/Settings.vue')['default']
    SettingsConnection: typeof import('./src/components/SettingsConnection.vue')['default']
    SettingsModel: typeof import('./src/components/SettingsModel.vue')['default']
    SettingsPreference: typeof import('./src/components/SettingsPreference.vue')['default']
    SettingsSummary: typeof import('./src/components/SettingsSummary.vue')['default']
    SettingsVLM: typeof import('./src/components/SettingsVLM.vue')['default']
    Showcases: typeof import('./src/components/Showcases.vue')['default']
    Sidebar: typeof import('./src/components/Sidebar.vue')['default']
    Step: typeof import('primevue/step')['default']
    StepList: typeof import('primevue/steplist')['default']
    StepPanel: typeof import('primevue/steppanel')['default']
    StepPanels: typeof import('primevue/steppanels')['default']
    Stepper: typeof import('primevue/stepper')['default']
    Tab: typeof import('primevue/tab')['default']
    TabList: typeof import('primevue/tablist')['default']
    TabPanel: typeof import('primevue/tabpanel')['default']
    TabPanels: typeof import('primevue/tabpanels')['default']
    Tabs: typeof import('primevue/tabs')['default']
    ToggleSwitch: typeof import('primevue/toggleswitch')['default']
    Wizard: typeof import('./src/components/Wizard.vue')['default']
  }
  export interface GlobalDirectives {
    Tooltip: typeof import('primevue/tooltip')['default']
  }
}
